# Site settings
title: Fab's blog
email: fan.torchz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  magic studio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.torchz.net" # the base hostname & protocol for your site
twitter_username: torchz
github_username:  tcz001

# Build settings
markdown: kramdown
